sitewomen/sitewomen/urls.py
from sys import exception

from django.conf.urls import handler404
from django.contrib import admin
from django.template.context_processors import request
from django.conf.urls.static import static
from . import settings
from django.urls import path, include

from sitewomen import settings
from women import views
from women.views import page_not_found

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('women.urls')),
    path('users/', include('users.urls', namespace="users")), #namespace - пространство имен, это дополнительно на свяк случай указывает, что эти URL работают только для приложения users
    path("__debug__/", include("debug_toolbar.urls")),
    path('social-auth/', include('social_django.urls', namespace='social')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404=page_not_found

admin.site.site_header = "Панель администрирования"
admin.site.index_title = "Известные женщины мира"

sitewomen/users/urls.py
from django.contrib.auth.views import LogoutView, PasswordChangeView, PasswordChangeDoneView, PasswordResetDoneView, \
    PasswordResetView, PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import path, reverse_lazy
from . import views

app_name = "users"

urlpatterns = [
    path('login/', views.LoginUser.as_view(), name='login'),
    path('logout/', views.logout_user, name='logout'),
    #path('logout/', LogoutView.as_view(), name='logout', #в джанго 5 уже нельзя!!! В джанго 5 запрещен логаут по гет-запросу),
    #path('register/', views.register, name='register'),
    path('password-change/', views.UserPasswordChange.as_view(), name='password_change'),
    path('password-change/done/', PasswordChangeDoneView.as_view(template_name="users/password_change_done.html"), name="password_change_done"),
    path('profile/', views.ProfileUser.as_view(), name='profile'),
    path('register/', views.RegisterUser.as_view(), name='register'),
    path('password-reset/',
         PasswordResetView.as_view(
             template_name="users/password_reset_form.html",
             email_template_name="users/password_reset_email.html",
             success_url=reverse_lazy("users:password_reset_done")
         ),
         name='password_reset'), #явно укажем свой шаблон, а не дефолтный
    path('password-reset/done/', PasswordResetDoneView.as_view(template_name = "users/password_reset_done.html"), name='password_reset_done'), #явно укажем свой шаблон, а не дефолтный
    path('password-reset/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(
             template_name="users/password_reset_confirm.html",
             success_url=reverse_lazy("users:password_reset_complete")), name='password_reset_confirm'),
    path('password-reset/complete/', PasswordResetCompleteView.as_view(template_name="users/password_reset_complete.html"), name='password_reset_complete'), #явно укажем свой шаблон, а не дефолтный
]
#если реализовывать функциями, а не классами
# path('logout/', views.login_user, name='login')
# path('logout/', views.logout_user, name='logout')

sitewomen/women/urls.py
from django.urls import path, re_path, register_converter
from . import views
from . import converters
from .views import WomenCategory

register_converter(converters.FourDigitYearConverter, "year4")

urlpatterns = [
    #path('', views.index, name='home'), #127.0.0.1:8000 name = алиас маршрута
    #path('about/', views.about, name='about'),
    #path('cats/<int:cat_id>/', views.categories, name='cats_id'), #127.0.0.1:8000/cats/cat_id
    #path('cats/<slug:cat_slug>/', views.categories_by_slug, name='cats'), #127.0.0.1:8000/cats/cat_id
    #re_path(r'^archive/(?P<year>[0-9]{4})/', views.archive, name='archive'), #127.0.0.1:8000/archive????
    #path('archive/<year4:year>/', views.archive, name='archive'), #127.0.0.1:8000/archive???? то же с помощью конвертера 'year4'
    #path('', views.index, name='home'),
    path('', views.WomenHome.as_view(), name='home'),#'при вызове можно переопределить переменную extra_context, которая была объявлена при объявлении класса и передать при вызове объекта класса WomenHome.as_view(extra_context={'title': "Главная страница сайта"})
    path('about/', views.about, name='about'),
    #path('addpage/', views.addpage, name='add_page'), # через функцию
    path('addpage/', views.AddPage.as_view(), name='add_page'),# через класс
    path('contact/', views.contact, name='contact'),
    path('login/', views.login, name='login'),
    #path('post/<int:post_id>/', views.show_post, name='post'), # маршрут с показом статей
    #path('post/<slug:post_slug>/', views.show_post, name='post'),
    path('post/<slug:post_slug>/', views.ShowPost.as_view(), name='post'),
    #path('cats/<int:cat_id>/', views.show_category, name='category'), категории по номерам
    #path('cats/<slug:cat_slug>/', views.show_category, name='category'),
    path('category/<slug:cat_slug>/', WomenCategory.as_view(), name='category'),
    #path('tag/<slug:tag_slug>/', views.show_tag_postlist, name='tag',
    #path('edit/<int:pk>/', views.UpdatePage.as_view(), name='edit_page'),
    path('edit/<slug:slug>/', views.UpdatePage.as_view(), name='edit_page'),
    path('tag/<slug:tag_slug>/', views.TagPostList.as_view(), name='tag',)
]

sitewomen/women/models.py
from django.contrib.auth import get_user_model
from django.core.validators import MinLengthValidator, MaxLengthValidator
from django.db import models
from django.template.defaultfilters import slugify
from django.urls import reverse


def translit_to_eng(s: str) -> str:
    d = {'а': 'a', 'б': 'b', 'в': 'v', 'г': 'g', 'д': 'd',
         'е': 'e', 'ё': 'yo', 'ж': 'zh', 'з': 'z', 'и': 'i', 'к': 'k',
         'л': 'l', 'м': 'm', 'н': 'n', 'о': 'o', 'п': 'p', 'р': 'r',
         'с': 's', 'т': 't', 'у': 'u', 'ф': 'f', 'х': 'h', 'ц': 'c', 'ч': 'ch',
         'ш': 'sh', 'щ': 'shch', 'ь': '', 'ы': 'y', 'ъ': '', 'э': 'r', 'ю': 'yu', 'я': 'ya'}

    return "".join(map(lambda x: d[x] if d.get(x, False) else x, s.lower()))

class PublishedModel(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(is_published=Women.Status.PUBLISHED)

# Create your models here.
class Women(models.Model):
    class Status(models.IntegerChoices):
        DRAFT = 0, 'Черновик'
        PUBLISHED = 1, 'Опубликовано'

    title = models.CharField(max_length=255, verbose_name="Заголовок", validators=[
        MinLengthValidator(5, message="Минимум 5 символов"),
        MaxLengthValidator(100, message="Максимум 100 символов"),
    ])#валидаторы так же как и валидаторы в Forms
    slug = models.SlugField(max_length=255, unique=True, db_index=True)
    photo = models.ImageField(upload_to="photos/%Y/%m/%d/", default=None, blank=True, null=True, verbose_name="Фото")
    content = models.TextField(blank=True, verbose_name="Текст статьи")
    time_create = models.DateTimeField(auto_now_add=True, verbose_name="Время создания")
    time_update = models.DateTimeField(auto_now=True, verbose_name="Время изменения")
    is_published = models.BooleanField(choices=tuple(map(lambda x: (bool(x[0]), x[1]), Status.choices)),
                                       default=Status.DRAFT, verbose_name="Статус")# костыль, потому, нужно перевести  0 и 1 из class Status(models.IntegerChoices) в булевые значения
    cat = models.ForeignKey('Category', on_delete=models.PROTECT, related_name='posts', verbose_name="Категории") #'posts' это алиас для women_set - вторичной модели
    #Класс 'Category' указан в виде строки т.к. в виде ссылки его еще может не существовать, н, вообще, если б был создан заранее, то можно передать через ссылку. PTOTECT -это ФУНКЦИЯ!
    tags = models.ManyToManyField('TagPost', blank=True, related_name='tags', verbose_name="Тэги") #on_delete в этом классе отсутствует
    husband = models.OneToOneField('Husband', on_delete=models.SET_NULL, null=True, blank=True, related_name='wuman', verbose_name="Муж")#'wuman' - это алиса для обратногно связывания т.е. из связанного класса получить доступ связанным объектам Women
    author = models.ForeignKey(get_user_model(), on_delete=models.SET_NULL, related_name='posts', null=True, default=None)#get_user_model() ищет в проекте модель user


    objects = models.Manager() #старый дефолтный менеджер менеджер, существует без объявления класса
    published = PublishedModel() #новый менеджер


    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Известные женщины'
        verbose_name_plural = 'Известные женщины'
        ordering=['-time_create']
        indexes=[models.Index(fields=['-time_create'])
        ]



    def get_absolute_url(self):
        return reverse('post', kwargs={'post_slug': self.slug})

    #def save(self, *args, **kwargs):
    #    self.slug = slugify(translit_to_eng(self.title , allow_unicode=True))
    #    super().save(*args, **kwargs)


class Category(models.Model):
    name = models.CharField(max_length=100, db_index=True, verbose_name="Категория")
    slug = models.SlugField(max_length=255, unique=True, db_index=True)

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def get_absolute_url(self):
        return reverse('category', kwargs={'cat_slug': self.slug}) #маршрут 'category' + параметр slug из поля slug вызываемого объекта

    def __str__(self):
        return self.name


class TagPost(models.Model):
    tag = models.CharField(max_length=100, db_index=True)
    slug = models.SlugField(max_length=255, unique=True, db_index=True)

    def get_absolute_url(self):
        return reverse('tag', kwargs={'tag_slug': self.slug})

    def __str__(self):
        return self.tag


class Husband(models.Model):
    name = models.CharField(max_length=100)
    age = models.IntegerField(null=True)
    m_count = models.IntegerField(blank=True, default=0)

    def __str__(self):
        return self.name

class UploadFiles(models.Model):
    file = models.FileField(upload_to='uploads_model') #указываем, куда загружать

sitewomen/women/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.core.validators import MaxLengthValidator, MinLengthValidator
from django.utils.deconstruct import deconstructible


from .models import Category, Husband, Women


@deconstructible
class RussianValidator: #создаем свой валидатор
    ALLOWED_CHARS = "АБВГДЕЁЖЗИЙКЛМНОПРСТУФХЦЧШЩЬЫЪЭЮЯабвгдеёжзийклмнопрстуфхцчшщбыъэюя0123456789- "
    code = 'russian'

    def __init__(self, message=None):
        self.message = message if message else "Должны присутствовать только русские символы, дефис и пробел."

    def __call__(self, value):
        if not (set(value) <= set(self.ALLOWED_CHARS)):
            raise ValidationError(self.message, code=self.code, params={"value": value})

# class AddPostForm(forms.Form): #форма не связана с моделью
#     title = forms.CharField(max_length=255, min_length=5, label="Заголовок",
#                             widget=forms.TextInput(attrs={'class': 'form-input'}),
#                             validators=[RussianValidator(),], #пользовательский валидатор
#                             error_messages={
#                                 'min_length': 'Слишком короткий заголовок',
#                                 'required': 'Без заголовка - никак',
#                             })#виджет указывает на доп. атрибуты,например CSS поля ввода; error_messages - словарь{название валидатора: сообщение при его нарушении}
#     slug = forms.SlugField(max_length=255, label="URL", validators=[
#         MinLengthValidator(5, message="Минимум 5 символов"),
#         MaxLengthValidator(100, message="Максимум 100 символов"),
#     ])#переопределяем валидаторы от валидаторов базового класса на свои собственные
#     content = forms.CharField(widget=forms.Textarea(attrs={'cols': 50, 'rows': 5}), required=False, label="Контент")#виджет указывает на доп. атрибуты,например размер поля ввода
#     is_published = forms.BooleanField(required=False, initial=True, label="Статус")
#     cat = forms.ModelChoiceField(queryset=Category.objects.all(), empty_label="Категория не выбрана", label="Категории")
#     husband = forms.ModelChoiceField(queryset=Husband.objects.all(), empty_label="Не замужем", required=False, label="Муж")
#
#     def clean_title(self): # будет вызываться проверка clean_нужное поле формы, это как замена своему классу валидатора. Для использолвания в одном месте
#         title = self.cleaned_data['title'] #все методы с ключевым словом cleaned вызываются автоматически при созадния экземпляра класса формы
#         ALLOWED_CHARS = "АБВГДЕЁЖЗИЙКЛМНОПРСТУФХЦЧШЩЬЫЪЭЮЯабвгдеёжзийклмнопрстуфхцчшщбыъэюя0123456789- "
#         if not (set(title) <= set(ALLOWED_CHARS)):
#             raise ValidationError("Должны быть только русские символы, дефис и пробел.")
#
#         return title


class AddPostForm(forms.ModelForm):
    cat = forms.ModelChoiceField(queryset=Category.objects.all(), empty_label="Категория не выбрана", label="Категории")#эти поля нужны, чтобы указать параметр значения по умолчанию в форме
    husband = forms.ModelChoiceField(queryset=Husband.objects.all(), empty_label="Не замужем", required=False,label="Муж")#эти поля нужны, чтобы указать параметр значения по умолчанию в форме

    class Meta:
        model = Women
        #fields = '__all__' #в форме появятся все поля модели, заполняемых автоматический, заголовок поля формы будет verbouse_name модели
        fields = ['title', 'slug', 'content', 'photo', 'is_published', 'cat', 'husband', 'tags']#лучше указать явно
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-input'}),
            'content': forms.Textarea(attrs={'cols': 50, 'rows': 5})}#виджеты с параметрами стилей
        labels = {'slug': 'URL'}#переопределим заголовок с verbouse_name на свой

    def clean_title(self): #все методы с ключевым словом cleaned вызываются автоматически при созадния экземпляра класса формы
        title = self.cleaned_data['title']
        if len(title) > 50:
            raise ValidationError('Длина превышает 50 символов')

        return title

class UploadFileForm(forms.Form):
    #file = forms.FileField(label="Файл", required=False)
    file = forms.ImageField(label="Изображение", required=False)

sitewomen/women/templates/women/about.html
{% extends 'base.html' %}

{% block content %}
<h1>{{title}}</h1>
{% for item in page_obj %}
{{ item.pk }}: {{ item.title }}</p>
{% endfor %}
<nav>
    <ul>
        {% for p in page_obj.paginator.page_range %}
        <li>
            <a href="?page={{ p }}">{{ p }}</a>
        </li>
        {% endfor %}
    </ul>
</nav>
{% endblock %}

sitewomen/women/templates/women/addpage.html
{% extends 'base.html' %}
 
{% block content %}
<h1>{{title}}</h1>
<form action="" method="post" enctype="multipart/form-data"><!--enctype="multipart/form-data" обязательно для добавления файлов -->
    {% csrf_token %}
    <!--можно так, но без CSS  {{ form.as_p }} - это as_p -  формы из объекта form через абзац, можно as_ul; as_table -->

        <div class="form-error">{{ form.non_field_errors }}</div>
    {% for f in form %}
        <label class="form-label" for="{{ f.id_for_label }}">{{f.label}}: </label>{{ f }}</p>
        <div class="form-error">{{ f.errors }}</div>
    {% endfor %}
    <button type="submit">Отправить</button></p>
</form>
{% endblock %}

sitewomen/women/templates/women/index.html
{% extends 'base.html' %}

{% block content %}
<ul class="list-articles">
	{% for p in posts %}
			<li><div class="article-panel">
	<p class="first">Категория: {{p.cat.name}} | автор: {{p.author.username|default:"неизвестен"}}</p>
	<p class="last">Дата: {{p.time_update|date:"d-m-Y H:i:s"}}</p>
    </div>
				{% if p.photo %}
                   <p ><img class="img-article-left thumb" src="{{p.photo.url}}"></p>
				{% endif %}
				<h2>{{p.title}}</h2>
    {% autoescape off %}
	{{p.content|linebreaks|truncatewords:40}}
    {% endautoescape %}
			<div class="clear"></div>
			<p class="link-read-post"><a href="{{ p.get_absolute_url }}">Читать пост</a></p>
			</li>
	{% endfor %}
</ul>
{% endblock %}


{% block navigation %}
{% if page_obj.has_other_pages %}
<nav class="list-pages">
    <ul>
		{% if page_obj.has_previous %}
		<li class="page-num">
			<a href="?page={{ page_obj.previous_page_number }}">&lt;</a>
		</li>
		{% endif %}

        {% for p in paginator.page_range %}
		{% if page_obj.number == p %}
		<li class="page-num page-num-selected">{{ p }}</li>
		{% elif p >= page_obj.number|add:-2 and p <= page_obj.number|add:2 %}
        <li class="page-num">
            <a href="?page={{ p }}">{{ p }}</a>
        </li>
		{% endif %}
        {% endfor %}

		{% if page_obj.has_next %}
		<li class="page-num">
			<a href="?page={{ page_obj.next_page_number }}">&gt;</a>
		</li>
		{% endif %}

    </ul>
</nav>
{% endif %}
{% endblock %}

sitewomen/women/templates/women/list_categories.html
{% for cat in cats %}
         {% if cat.id == cat_selected %}
                   <li class="selected">{{cat.name}}</li>
         {% else %}
                   <li><a href="{{ cat.get_absolute_url }}">{{cat.name}}</a></li>
         {% endif %}
{% endfor %}

sitewomen/women/templates/women/list_tags.html
{% if tags %}
    Теги:</p>
    <ul class="tags-list">
        {% for t in tags %}
        <li><a href="{{t.get_absolute_url}}">{{t.tag}}</a></li>
        {% endfor %}
    </ul>
{% endif %}

sitewomen/women/templates/women/post.html
{% extends 'base.html' %}

{% block breadcrumbs %}

{% if perms.women.change_women %}
<p ><a href="{% url 'edit_page' post.slug %}">Редактировать</a></p>
{% endif %}
<!-- Теги -->
{% with post.tags.all as tags %}
{% if tags %}
<ul class="tags-list">
    <li>Теги:</li>
    {% for t in tags %}
    <li><a href="{{t.get_absolute_url}}">{{t.tag}}</a></li>
    {% endfor %}
</ul>
{% endif %}
{% endwith %}
{% endblock %}

{% block content %}
<h1>{{post.title}}</h1>

{% if post.photo %}
<p><img class="img-article-left" src="{{post.photo.url}}"></p>
{% endif %}

{{post.content|linebreaks}}
{% endblock %}